### ISSUE TITLE
Compilation with Craftr

### ISSUE THREAD

**Issue by NiklasRosenstein** [geomalgo/geomalgo#1]
Hi David,

since you're trying to compile Cython projects with [Craftr](https://github.com/craftr-build/craftr), I thought I could try it myself to see how it works out with a real world project. The Craftr standard library is not 100% easy to use for Cython projects, but I figured I'd show you a script that worked for me on Windows and eventually that will help you set it up for Linux.

Note that I did some adjustments that are required to run this script, you need at least a Craftr installation that includes commit [ad5fdb7](https://github.com/craftr-build/craftr/commit/ad5fdb7b3aa1398df3d317e1bbea1cbc30a80bd0).

I recognize that this is of course not ideal and there is plenty of room for improvements. But it's a matter of thinking about a good way to abstract the compilation in a way that it's still very customizable and also a matter of time to implement and test these things.

`Craftfile.py`

``` python
# craftr_module(geomalgo)

from craftr import path, options, Framework
from craftr.ext.compiler.cython import cythonc
from craftr.ext.platform import cxx, ld

cpp_files = cythonc.compile(
  py_sources = path.glob('geomalgo/**/*.pyx'),
  python_version = int(options.get('python_version', 3)),
  cpp = True,
)

# should be determined based on the OS
pyd_suffix = '.pyd'
python_fw = Framework(
  include = ['F:/Python34/include'],
  libpath = ['F:/Python34/libs']
)

# path to the output directory of the C/C++ files from Cython
cython_outdir = cpp_files.meta['cython_outdir']
module_dir = path.local('geomalgo')

for fn in cpp_files.outputs:
  # Transform the output filename from the C/C++ output file directory
  # to the local module directory.
  outfile = path.join(module_dir, path.relpath(fn, cython_outdir))
  outfile = path.setsuffix(outfile, pyd_suffix)

  ld.link(
    output = outfile,
    output_type = 'dll',
    keep_suffix = True,  # don't let link() replace the suffix with one appropriate for the OS (eg. dll on Windows)
    inputs = cxx.compile(
      sources = [fn],
      frameworks = [python_fw],
    ),
  )
```

Let me know if you have any questions/problems/suggestions.

**Comment by dfroger** [comment]
Thanks, interessing!

I'm trying to make it work on Linux, here is my [Craftfile.py](https://github.com/dfroger/geomalgo/blob/craftr/Craftfile.py).

I have two issues:
- `c/cpp` files must be compile with `-fPIC`
- `ld` must be invoked with `-shared` (otherwise, it's looking for a `main` function)

Where can set these `CFLAGS`, `CPPFLAGS`, `LDFLAGS`?

**Comment by dfroger** [comment]
Just fount in the [doc](http://craftr.readthedocs.io/en/latest/stl/compiler_llvm.html), in now build with this [Craftfile](https://github.com/dfroger/geomalgo/blob/craftr/Craftfile.py)

**Comment by NiklasRosenstein** [comment]
> c/cpp files must be compile with -fPIC

As I think you already found out, you can pass `pic=True` option to the `cxx.compile()` function. Does `-fPIC` also need to be passed when linking with GCC/Clang? I thought not, but if it does, I need to add this option to `ld.link()` as well.

> ld must be invoked with -shared (otherwise, it's looking for a main function)

`ld.link()` is intended to select the right flags when using `output_type='dll'` including the `-shared` flag. But I see now that the LLVM/GCC implementation currently does not. It passes `-dynamic` instead. Relevant code in `craftr.ext.compiler.llvm.py`

``` python
    command += ['-dynamic'] if output_type == 'dll' else []
```

I am unsure if I should replace `-dynamic` with `-shared` or just add `-shared`. Do you have a suggestion?

**Comment by NiklasRosenstein** [comment]
> Where can set these CFLAGS, CPPFLAGS, LDFLAGS?

Craftr usually doesn't use these variables, but can read them yourself and pass them to the `additional_flags`:

``` python
from craftr import shell, options
from craftr.ext.platform import ld
#...
ld.link(
    # ...
    additional_flags=shell.split(options.get('LDFLAGS', '')),
)
```

Then you can either set `LDFLAGS` globally via the environment variables or locally only for your module like this:

```
craftr -DLDFLAGS="..."          # global
craftr -D.LDFLAGS="..."         # local
craftr -Dgeomalgo.LDFLAGS="..." # local
```

**Comment by NiklasRosenstein** [comment]
Submitting patches for this single file sounds like overkill so I'll just make some comments about the Craftfile here.

I suggest you do the platform check like this:

``` python
from craftr import *   # can be used if you need more than just path, options, Framework etc.
from craftr.ext.platform import name as platform_name

if platform_name == 'linux':
  # ...
elif platform_name == 'win':
  # ...
elif platform_name == 'mac':
  # ...
else:
  error('unsupported platform: {!r}'.format(platform_name))
```

Also, I think we can find out all the information we need about Python using `distutils`. This would get around the hardcoded data that highly depends on the machine you're using. Let me look into that some more.

```
λ python -c "import distutils.sysconfig; print(distutils.sysconfig.get_config_vars())"
{'VERSION': '34', 'SO': '.pyd', 'INCLUDEPY': 'F:\\Python34\\include', 'EXT_SUFFIX': '.pyd', 'BINDIR': 'F:\\Python34', 'srcdir': 'F:\\Python34', 'EXE': '.exe', 'LIBDEST': 'F:\\Python34\\Lib', 'exec_prefix': 'F:\\Python34', 'prefix': 'F:\\Python34', 'BINLIBDEST': 'F:\\Python34\\Lib'}
```

**Comment by NiklasRosenstein** [comment]
I've just added the `craftr.ext.python` standard library module in Craftr@[cbdae36](https://github.com/craftr-build/craftr/commit/cbdae36). It looks a lot more concise now :) And you can specify which Python version to build for from the command-line:

```
craftr -e -DPYTHON=python3.5
```

``` python
# craftr_module(geomalgo)

from craftr import path, options, error, Framework
from craftr.ext.compiler.cython import cythonc
from craftr.ext import platform, python

cpp_files = cythonc.compile(
  py_sources = path.glob('geomalgo/**/*.pyx'),
  python_version = int(options.get('python_version', 3)),
  cpp = True,
)

pybin = options.get('PYTHON', 'python')
pyd_suffix = python.get_python_config_vars(pybin)['SO']
python_fw = python.get_python_framework(pybin)

# path to the output directory of the C/C++ files from Cython
cython_outdir = cpp_files.meta['cython_outdir']
module_dir = path.local('geomalgo')

for fn in cpp_files.outputs:
  # Transform the output filename from the C/C++ output file directory
  # to the local module directory.
  outfile = path.join(module_dir, path.relpath(fn, cython_outdir))
  outfile = path.setsuffix(outfile, pyd_suffix)

  platform.ld.link(
    output = outfile,
    output_type = 'dll',
    keep_suffix = True,  # don't let link() replace the suffix with one appropriate for the OS (eg. dll on Windows)
    inputs = platform.cxx.compile(
      sources = [fn],
      frameworks = [python_fw],
    ),
    pic = True,
    additional_flags = ['-shared'],
  )
```

**Comment by dfroger** [comment]
> As I think you already found out, you can pass pic=True option to the cxx.compile() function. Does -fPIC also need to be passed when linking with GCC/Clang? I thought n
> ot, but if it does, I need to add this option to ld.link() as well.

I think you're right, -fPIC is for the compiler only, not the linker.

> I am unsure if I should replace -dynamic with -shared or just add -shared. Do you have a suggestion?

I would say that for GCC on Gnu/Linux, -shared only is good.

The GCC manual says that -dynamic is passed to the Darwin linker. Maybe usefull before [Xcode version 5, when Apple had support for gcc](https://support.enthought.com/hc/en-us/articles/204469410-OS-X-GCC-Clang-and-Cython-in-10-9-Mavericks)?

> > Where can set these CFLAGS, CPPFLAGS, LDFLAGS?
> 
> Craftr usually doesn't use these variables, but can read them yourself and pass them to the additional_flags:

I'm wondering to what extent Craftr can natively give total control to package manager.  If these variables may or may not be available (depending on how the Craftfile is written), isn't it a problem?  Autotools always take these variables into account, meson do the same (see this [doc](https://github.com/mesonbuild/meson/wiki/Quick%20guide#using-meson-as-a-distro-packager)). I think SCons has been criticized to not have this behaviour.

Is it a design in Craftr to allow package manager to have full control of compiler and linker flags?

Having the possibility to set these variables via environment variable locally or globally is really great!

> I've just added the craftr.ext.python standard library module in Craftr@cbdae36. It looks a lot more concise now :

Thanks a lot! I will read it in detail, as well as Craftr documentation.

**Comment by NiklasRosenstein** [comment]
> I would say that for GCC on Gnu/Linux, -shared only is good.
> 
> The GCC manual says that -dynamic is passed to the Darwin linker. Maybe usefull before Xcode version 5, when Apple had support for gcc?

Thanks for the info! So maybe just include the `-dynamic` flag on OSX then. I'll do some more research.

If you remove the `additional_flags = ['-shared']` from the Craftfile on your Linux system, does it still link successfully? Or is the result not a shared library?

> I'm wondering to what extent Craftr can natively give total control to package manager. If these variables may or may not be available (depending on how the Craftfile is written), isn't it a problem? Autotools always take these variables into account, meson do the same (see this doc). I think SCons has been criticized to not have this behaviour.

First let me tell you that I am unexperienced with linux packages. :) So I don't know if it will be a problem if the Craftfile wasn't written to support `CFLAGS`, etc. For example, wouldn't it be a common case that the `CFLAGS` should only apply to parts of the software build, not all of it?

Also, Craftr currently uses the same program to compile **and** link on Linux and Mac OS (ie. Clang/GCC), so it doesn't actually use `ld`. Would the `LDFLAGS` still be passable to these or would they need to be passed to clang/gcc with `-Wl,` to end up with the linker?

> Is it a design in Craftr to allow package manager to have full control of compiler and linker flags?

I haven't thought about this before, but I think it would be a good point to do this and eventually support everything that (a) package manager(s) need/want.

> Having the possibility to set these variables via environment variable locally or globally is really great!

Luckily, automatically supporting `CFLAGS`, `CPPFLAGS`, etc would be very easy. They would just need to be read from the `compile()` methods of the compiler implementation (`MsvcCompiler`, `LlvmCompiler`). I'll open an issue to support these flags by default and that there needs to be an option to disable handling these flags if desired.

---

By the way, did you receive my patch for the Craftfile by email?

**Comment by dfroger** [comment]
> If you remove the additional_flags = ['-shared'] from the Craftfile on your Linux system, does it still link successfully? Or is the result not a shared library?

The [Craftfile](https://github.com/dfroger/geomalgo/blob/2ad692439e15353b39ceaa1a0dac6419a65207c1/Craftfile.py) from your pull request, with the [last](https://github.com
/craftr-build/craftr/commit/643540d7619fa1fbd3740850d6e76311bffc94aa) version of Craftr works perfectly on my Linux system!

I will add Travis tests for GNU/Linux and OSX.

> First let me tell you that I am unexperienced with linux packages. :) So I don't know if it will be a problem if the Craftfile wasn't written to support CFLAGS, etc. Fo
> r example, wouldn't it be a common case that the CFLAGS should only apply to parts of the software build, not all of it?
> 
> Also, Craftr currently uses the same program to compile and link on Linux and Mac OS (ie. Clang/GCC), so it doesn't actually use ld. Would the LDFLAGS still be passable
>  to these or would they need to be passed to clang/gcc with -Wl, to end up with the linker?

I'm not to experienced linux packager too, but I'll try to get informations from one!

> By the way, did you receive my patch for the Craftfile by email?

No! Did you sent it to david.froger@mailoo.org?

**Comment by NiklasRosenstein** [comment]
> The Craftfile from your pull request, with the last version of Craftr works perfectly on my Linux system!
> 
> I will add Travis tests for GNU/Linux and OSX.

Great! :)

> No! Did you sent it to david.froger@mailoo.org?

I think I did, I was using `git format-patch` and `git send-email`. I was using `git send-email` the fir time, though. Anyway, it was the same as PR #2. :)

> I'm not to experienced linux packager too, but I'll try to get informations from one!

Thanks for your efforts! Just for the sake of completeness, I'll link to the CFLAGS discussion here: craftr-build/craftr#111

**Comment by dfroger** [comment]
I've merged the branch into master, and now use `Craftr` to build the project.

Thanks a lot for your help!
